### ISSUE TITLE
Interrupt request

### ISSUE THREAD

**Issue by garudaonekh** [nopnop2002/Arduino-LoRa-Ra01S#13]
Hi,
How to add interrupt to this library?

I want to sleep the MCU and wakeup it when there's incoming data.

I use PY32F002 chip.

Regards;

**Comment by nopnop2002** [comment]
Please read the SX126x datasheet.


All the answers are here.

https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R0000001Rbr/6EfVZUorrpoKFfvaF_Fkpgp5kzjiNyiAbqcpqh9qSjE

**Comment by garudaonekh** [comment]
Thanks;
