### ISSUE TITLE
Question on SPI migration from Arduino to ESP8266

### ISSUE THREAD

**Issue by garudaonekh** [nopnop2002/Arduino-LoRa-Ra01S#14]
Hi,
I see you mentioned in your description that this library is migrated from Arduino.

I want to migrate a SPI LORA from Arduino to ESP8266 too. It compile successfully but it failed to read from the LORA registry. I think there must be some change to make.

Do you have some suggetion?
Thanks;

**Comment by nopnop2002** [comment]
GPIO used as SPI is different between ATmega328/2560 and ESP8266.

**Comment by garudaonekh** [comment]
Thanks
